// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v4.23.4
// source: proto/schema_registry.proto

package schemaregistry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Format int32

const (
	Format_FORMAT_JSON Format = 0
	Format_FORMAT_AVRO Format = 1
)

// Enum value maps for Format.
var (
	Format_name = map[int32]string{
		0: "FORMAT_JSON",
		1: "FORMAT_AVRO",
	}
	Format_value = map[string]int32{
		"FORMAT_JSON": 0,
		"FORMAT_AVRO": 1,
	}
)

func (x Format) Enum() *Format {
	p := new(Format)
	*p = x
	return p
}

func (x Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Format) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_schema_registry_proto_enumTypes[0].Descriptor()
}

func (Format) Type() protoreflect.EnumType {
	return &file_proto_schema_registry_proto_enumTypes[0]
}

func (x Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Format.Descriptor instead.
func (Format) EnumDescriptor() ([]byte, []int) {
	return file_proto_schema_registry_proto_rawDescGZIP(), []int{0}
}

type ValidateEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventSchemaId string `protobuf:"bytes,1,opt,name=event_schema_id,json=eventSchemaId,proto3" json:"event_schema_id,omitempty"`
	Payload       []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Format        Format `protobuf:"varint,3,opt,name=format,proto3,enum=schemaregistrygrp.Format" json:"format,omitempty"`
}

func (x *ValidateEventRequest) Reset() {
	*x = ValidateEventRequest{}
	mi := &file_proto_schema_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateEventRequest) ProtoMessage() {}

func (x *ValidateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schema_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateEventRequest.ProtoReflect.Descriptor instead.
func (*ValidateEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_schema_registry_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateEventRequest) GetEventSchemaId() string {
	if x != nil {
		return x.EventSchemaId
	}
	return ""
}

func (x *ValidateEventRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ValidateEventRequest) GetFormat() Format {
	if x != nil {
		return x.Format
	}
	return Format_FORMAT_JSON
}

type ValidateEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid   bool   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ValidateEventResponse) Reset() {
	*x = ValidateEventResponse{}
	mi := &file_proto_schema_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateEventResponse) ProtoMessage() {}

func (x *ValidateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schema_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateEventResponse.ProtoReflect.Descriptor instead.
func (*ValidateEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_schema_registry_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateEventResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_schema_registry_proto protoreflect.FileDescriptor

var file_proto_schema_registry_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x5f, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x67, 0x72, 0x70,
	0x22, 0x8b, 0x01, 0x0a, 0x14, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x31, 0x0a, 0x06, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x67, 0x72, 0x70, 0x2e,
	0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x22, 0x47,
	0x0a, 0x15, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x2a, 0x0a, 0x06, 0x46, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x12, 0x0f, 0x0a, 0x0b, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x5f, 0x4a, 0x53, 0x4f, 0x4e,
	0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x5f, 0x41, 0x56, 0x52,
	0x4f, 0x10, 0x01, 0x32, 0x74, 0x0a, 0x0e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x79, 0x12, 0x62, 0x0a, 0x0d, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x27, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x67, 0x72, 0x70, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x28, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79,
	0x67, 0x72, 0x70, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x25, 0x5a, 0x23, 0x2e, 0x2f, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x67, 0x72, 0x70,
	0x63, 0x3b, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_schema_registry_proto_rawDescOnce sync.Once
	file_proto_schema_registry_proto_rawDescData = file_proto_schema_registry_proto_rawDesc
)

func file_proto_schema_registry_proto_rawDescGZIP() []byte {
	file_proto_schema_registry_proto_rawDescOnce.Do(func() {
		file_proto_schema_registry_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_schema_registry_proto_rawDescData)
	})
	return file_proto_schema_registry_proto_rawDescData
}

var file_proto_schema_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_schema_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_schema_registry_proto_goTypes = []any{
	(Format)(0),                   // 0: schemaregistrygrp.Format
	(*ValidateEventRequest)(nil),  // 1: schemaregistrygrp.ValidateEventRequest
	(*ValidateEventResponse)(nil), // 2: schemaregistrygrp.ValidateEventResponse
}
var file_proto_schema_registry_proto_depIdxs = []int32{
	0, // 0: schemaregistrygrp.ValidateEventRequest.format:type_name -> schemaregistrygrp.Format
	1, // 1: schemaregistrygrp.SchemaRegistry.ValidateEvent:input_type -> schemaregistrygrp.ValidateEventRequest
	2, // 2: schemaregistrygrp.SchemaRegistry.ValidateEvent:output_type -> schemaregistrygrp.ValidateEventResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_schema_registry_proto_init() }
func file_proto_schema_registry_proto_init() {
	if File_proto_schema_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_schema_registry_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_schema_registry_proto_goTypes,
		DependencyIndexes: file_proto_schema_registry_proto_depIdxs,
		EnumInfos:         file_proto_schema_registry_proto_enumTypes,
		MessageInfos:      file_proto_schema_registry_proto_msgTypes,
	}.Build()
	File_proto_schema_registry_proto = out.File
	file_proto_schema_registry_proto_rawDesc = nil
	file_proto_schema_registry_proto_goTypes = nil
	file_proto_schema_registry_proto_depIdxs = nil
}
